token:
  expiration_time: 86400000
  secret: '{cipher}AQBNQapRiP8u1VX0mCPXdHjpBij2YufeKxbSrZSKUAfxA2pwyLKfHQyh035GLYi6WgfmhwECLSbk86VLoLkdGWHQ4eB8ABmwPXqdtkKI2Orh/HS+P8H8MtOBBhHZNG6ULXeE16+zv1rlhGYWhCYWNINOlI6jRAGsraFwcbfMe/dEB4c5xrHvrS/HB2Z4Ni2HO7Cc8S9eYLOhW2JKVw6vbdumhyssWx4axBzcdS0CsBIjaE9EZl1ckUY6cmiMQndyX81yWxR/9kD512z6VdebZwtpXHL7hSTwt0G38jPKUPUN6KmHrV6BXnJlfD85H2fxhLSM2AUoTx+hKZvgx9e7SCnb+MeuHluVEJuTasEdxS4/2M8vccKH45kLtqLOx9NmyO3fzoMCUthgRXu2RSI/1h+W'

gateway:
  ip: 192.168.137.1